nohup: 忽略输入
[I 16:07:57.416 NotebookApp] Serving notebooks from local directory: /home/saber/project/my_ml_service
[I 16:07:57.416 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 16:07:57.416 NotebookApp] http://localhost:8000/?token=c4c62a213fa055f965b291d7c8ff10b3f4d1c3bdc8142666
[I 16:07:57.416 NotebookApp]  or http://127.0.0.1:8000/?token=c4c62a213fa055f965b291d7c8ff10b3f4d1c3bdc8142666
[I 16:07:57.416 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:07:57.418 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/saber/.local/share/jupyter/runtime/nbserver-23413-open.html
    Or copy and paste one of these URLs:
        http://localhost:8000/?token=c4c62a213fa055f965b291d7c8ff10b3f4d1c3bdc8142666
     or http://127.0.0.1:8000/?token=c4c62a213fa055f965b291d7c8ff10b3f4d1c3bdc8142666
[I 16:09:17.383 NotebookApp] Creating new notebook in 
[I 16:09:18.551 NotebookApp] Kernel started: c4ebbe00-5beb-47e1-af71-c10988c61fb7, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 5170af3a-29fd-43c9-8317-1cad4e812fd7
[I 16:09:57.266 NotebookApp] Kernel interrupted: c4ebbe00-5beb-47e1-af71-c10988c61fb7
[I 16:09:57.466 NotebookApp] Kernel interrupted: c4ebbe00-5beb-47e1-af71-c10988c61fb7
[I 16:11:18.493 NotebookApp] Saving file at /Untitled.ipynb
/home/saber/anaconda3/envs/Django_env/lib/python3.7/site-packages/nbformat/__init__.py:129: MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)
/home/saber/anaconda3/envs/Django_env/lib/python3.7/site-packages/notebook/services/contents/manager.py:353: MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate_nb(model['content'])
[I 16:13:04.414 NotebookApp] Kernel interrupted: c4ebbe00-5beb-47e1-af71-c10988c61fb7
[I 16:13:04.583 NotebookApp] Kernel interrupted: c4ebbe00-5beb-47e1-af71-c10988c61fb7
[I 16:13:14.714 NotebookApp] Uploading file to /data_.csv
[I 16:13:18.486 NotebookApp] Saving file at /Untitled.ipynb
[I 16:15:18.528 NotebookApp] Saving file at /Untitled.ipynb
[I 16:25:18.440 NotebookApp] Saving file at /Untitled.ipynb
[I 16:27:18.499 NotebookApp] Saving file at /ML.ipynb
[I 16:28:28.113 NotebookApp] Creating new directory in 
[W 16:28:34.842 NotebookApp] 409 PATCH /api/contents/Untitled%20Folder (127.0.0.1): File already exists: research
[W 16:28:34.843 NotebookApp] File already exists: research
[W 16:28:34.844 NotebookApp] 409 PATCH /api/contents/Untitled%20Folder (127.0.0.1) 3.940000ms referer=http://localhost:8001/tree
[W 16:28:41.582 NotebookApp] delete /Untitled Folder
[I 16:29:32.493 NotebookApp] Starting buffering for c4ebbe00-5beb-47e1-af71-c10988c61fb7:a4a0499339ab493386e3fdbcc7cd4e53
